In [39]:
import numpy as np
import math

# Define environment
environment = np.zeros((3,4))
environment[1][1] = np.nan
environment[0][3] = 1
environment[1][3] = -1
newenvironment = environment.copy()

# Initialize variables
gamma = 0.9
theta = 0.000000000000001
delta = theta
row = len(environment) # 3
col = np.size(environment,1) # 4

# Delta will iteratively increase until greater than or equal to theta
while delta >= theta:

    delta = 0
    environment = newenvironment.copy()

    # Nested loops will check each element of the array
    for x in range(row):
        for y in range(col):

            # Check if the element is a positive state, negative state, or a "blocked" element
            if environment[x][y] != "nan" and environment[x][y] != 1 and environment[x][y] != -1:
                
                neighbors = []

                # Checking upper left corner
                if x == 0 and y == 0:
                    up = environment[x][y]
                    left = environment[x][y]
                    right = environment[x][y + 1]
                    down = environment[x + 1][y]

                # Checking upper row
                if x == 0 and (y != 0 and y != np.size(environment,1) - 1):
                    up = environment[x][y]
                    left = environment[x][y - 1]
                    right = environment[x][y + 1]
                    down = environment[x + 1][y]

                # Checking upper right corner
                if x == 0 and y == np.size(environment, 1) - 1:
                    up = environment[x][y]
                    left = environment[x][y - 1]
                    right = environment[x][y]
                    down = environment[x + 1][y]

                # Checking right column
                if y == (np.size(environment, 1) - 1) and (x != 0 and x != len(environment) - 1):
                    up = environment[x][y - 1]
                    left = environment[x][y - 1]
                    right = environment[x][y]
                    down = environment[x + 1][y]

                # Checking lower right corner
                if x == len(environment) - 1 and y == np.size(environment, 1) - 1:
                    up = environment[x - 1][y]
                    left = environment[x][y - 1]
                    right = environment[x][y]
                    down = environment[x][y]

                # Checking lower row
                if x == len(environment) - 1 and (y != 0 and y != np.size(environment, 1) - 1):
                    up = environment[x - 1][y]
                    left = environment[x][y - 1]
                    right = environment[x][y + 1]
                    down = environment[x][y]

                # Checking lower left corner
                if x == len(environment) - 1 and y == 0:
                    up = environment[x][y + 1]
                    left = environment[x][y]
                    right = environment[x][y + 1]
                    down = environment[x][y]

                # Checking left column
                if y == 0 and (x != 0 and x != len(environment) - 1):
                    up = environment[x - 1][y]
                    left = environment[x][y]
                    right = environment[x][y + 1]
                    down = environment[x + 1][y]
                
                # Checking in between cells
                if y != 0 and x!= 0 and x != len(environment) - 1 and y != np.size(environment, 1) - 1:
                    up = environment[x - 1][y]
                    left = environment[x][y - 1]
                    right = environment[x][y + 1]
                    down = environment[x + 1][y]
                
                # Store the immediate neighboring state values and sort them from lowest to highest
                neighbors = [up, down, left, right]
                sorted = sort(neighbors)

                # If there is a 1, -1, or nan value present, delete it. 
                if np.isnan(sorted).any():
                    sorted = np.delete(sorted, 3) # nan is the lowest value
                if sorted[0] == -1 and sorted[-1] == 0:
                    sorted = np.delete(sorted, 0)
                
                # Calculate the reward using the bellman equation
                reward = 0.8 * ( gamma * sorted[-1])
                for i in range(len(sorted) - 1):
                    reward += 0.1 * (gamma * sorted[-i-2])

                # If the element is nan, ignore. Otherwise, update new state value
                if np.isnan(newenvironment[x][y]):
                    continue
                else:
                    newenvironment[x][y] = round(reward, 2)

                # Find the updated delta value by taking the absolute difference between the new state value and the old state value
                if delta < abs((newenvironment[x][y] - environment[x][y])):
                    delta = (newenvironment[x][y] - environment[x][y])

    print("\n", newenvironment)
environment = newenvironment.copy()



 [[ 0.    0.    0.72  1.  ]
 [ 0.     nan  0.   -1.  ]
 [ 0.    0.    0.    0.  ]]

 [[ 0.    0.52  0.78  1.  ]
 [ 0.     nan  0.43 -1.  ]
 [ 0.    0.    0.    0.  ]]

 [[ 0.37  0.61  0.88  1.  ]
 [ 0.     nan  0.47 -1.  ]
 [ 0.    0.    0.31  0.  ]]

 [[ 0.51  0.72  0.9   1.  ]
 [ 0.27   nan  0.57 -1.  ]
 [ 0.    0.22  0.37  0.13]]

 [[ 0.63  0.76  0.92  1.  ]
 [ 0.39   nan  0.59 -1.  ]
 [ 0.18  0.29  0.48  0.2 ]]

 [[ 0.7   0.79  0.92  1.  ]
 [ 0.5    nan  0.62 -1.  ]
 [ 0.27  0.39  0.51  0.29]]

 [[ 0.74  0.8   0.93  1.  ]
 [ 0.57   nan  0.62 -1.  ]
 [ 0.36  0.43  0.55  0.33]]

 [[ 0.76  0.81  0.93  1.  ]
 [ 0.62   nan  0.63 -1.  ]
 [ 0.41  0.47  0.56  0.37]]

 [[ 0.78  0.81  0.93  1.  ]
 [ 0.64   nan  0.63 -1.  ]
 [ 0.45  0.48  0.58  0.38]]

 [[ 0.78  0.81  0.93  1.  ]
 [ 0.66   nan  0.63 -1.  ]
 [ 0.47  0.5   0.58  0.4 ]]

 [[ 0.78  0.81  0.93  1.  ]
 [ 0.66   nan  0.63 -1.  ]
 [ 0.49  0.5   0.59  0.4 ]]

 [[ 0.78  0.81  0.93  1.  ]
 [ 0.67   nan  0.63 -1.  ]
 [ 0.49  0.51  0.59 