In [31]:
import numpy as np
import random

# Create the initial environment with all states set to 0
environment = np.zeros((5,5))

# Initialize variables
gamma = 0.002
delta = 0
theta = 0.5

# Randomly define the blocked cells with nan
environment[random.randint(0, (len(environment) - 1))][random.randint(0, (len(environment) - 1))] = None

# Randomly define the desired terminal state
environment[random.randint(0, (len(environment) - 1))][random.randint(0, (len(environment) - 1))] = 1



while delta < theta:
    for x in range(len(environment)):
        for y in range(len(environment)):
            environment[x][y] += 

print(environment)

[[ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5. nan]
 [ 5.  5.  5.  5.  6.]
 [ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]]
